"""
========================================================
shot_ml_trainer.py — ML Shot Classifier Trainer
========================================================

WHAT THIS FILE DOES:
--------------------
Trains a multi-class Machine Learning model (Random Forest) to 
recognize different types of cricket shots (Cover Drive, Pull, etc.).
It uses the `shot_type` column generated by the heuristic rules in 
the dataset as training labels.

AUTHOR: Cricket Biomechanics Analyzer V2
"""

import os
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ml_trainer import MLTrainer

def train_shot_classifier():
    print("="*60)
    print("  CRICKET BIOMECHANICS — SHOT CLASSIFIER ML TRAINER")
    print("="*60)

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    dataset_path = os.path.join(base_dir, "data/cricket_biomechanics_dataset.csv")
    model_save_path = os.path.join(base_dir, "models/shot_classifier.pkl")
    
    if not os.path.exists(dataset_path):
        print(f"  ❌ ERROR: Dataset not found at {dataset_path}")
        return False

    print("  [1/4] Loading Dataset...")
    df = pd.read_csv(dataset_path)
    
    # We only care about rows where a shot was actually identified
    # Filter out 'Analyzing...' or 'Unknown'
    valid_shots = df[~df['shot_type'].isin(['Analyzing...', 'Unknown', 'Collecting data...'])].copy()
    
    if len(valid_shots) < 50:
        print(f"  ❌ ERROR: Not enough labeled shot data. Only found {len(valid_shots)} rows.")
        return False
        
    print(f"        Found {len(valid_shots)} valid frames with identified shots.")
    
    # 2. Features and Labels
    print("  [2/4] Preparing Features & Labels...")
    available_features = [f for f in MLTrainer.FEATURE_COLUMNS if f in valid_shots.columns]
    
    X = valid_shots[available_features].fillna(0.0)
    y = valid_shots['shot_type']
    
    print("\n        Shot Distribution:")
    print(y.value_counts())
    print()

    # 3. Train/Test split
    print("  [3/4] Splitting Data (80% Train, 20% Test)...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # 4. Train model
    print("  [4/4] Training Random Forest Shot Classifier...")
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42,
        n_jobs=-1
    )
    model.fit(X_train, y_train)

    # Evaluate
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    
    print("\n  " + "="*50)
    print(f"  [RF] Shot Classification Accuracy : {acc*100:.2f}%")
    print("  " + "="*50 + "\n")
    
    print(classification_report(y_test, y_pred, zero_division=0))

    # Save model
    os.makedirs(os.path.dirname(model_save_path), exist_ok=True)
    joblib.dump(model, model_save_path)
    
    print(f"\n  [SAVED] Shot Classifier -> {model_save_path}")
    print("="*60 + "\n")

if __name__ == "__main__":
    train_shot_classifier()
